 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Kholoud Galal
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/*  #Structure to configure each individual PIN:
 *      1. Port Number -->[A,B,C,D,E,F].
 *      2. Pin Number -->[A0,A1,A2,A3,A4,A5,A6,A7......F7].
 *	3. Direction of pin -->[INPUT Direction/OUTPUT Direction].
 *      4. Pin Mode -->[DIO/ADC/UART/ .... PWM].
 *      5. Initial value -->[STD_HIGH/STD_LOW].
 *      6. Internal resistor -->[Disabled/Internal Pull up/Internal Pull down].
 *      7. Pin direction changeability -->[STD_HIGH/STD_LOW].
 *      8. Pin mode changeability -->[STD_HIGH/STD_LOW].
 */
const Port_ConfigType Port_pinConfiguration= {
  
         /*****************************************PORT A*******************************************/ 
	 PORT_A_ID,PIN_A0_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A1_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A2_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A3_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A4_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A5_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A6_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_A_ID,PIN_A7_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         /*****************************************PORT B*******************************************/ 
         PORT_B_ID,PIN_B0_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B1_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B2_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B3_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B4_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B5_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B6_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_B_ID,PIN_B7_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         /*****************************************PORT C*******************************************/ 
	 PORT_C_ID,PIN_C0_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C1_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C2_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C3_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C4_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C5_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C6_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_C_ID,PIN_C7_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         /*****************************************PORT D*******************************************/ 
         PORT_D_ID,PIN_D0_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D1_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D2_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D3_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D4_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D5_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D6_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_D_ID,PIN_D7_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         /*****************************************PORT E*******************************************/ 
         PORT_E_ID,PIN_E0_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E1_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E2_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E3_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E4_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E5_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E6_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_E_ID,PIN_E7_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         /*****************************************PORT F*******************************************/ 
         PORT_F_ID,PIN_F0_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,         
         PORT_F_ID,PIN_F1_ID,PORT_PIN_OUT,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_LOW,STD_LOW,  /*[LED Connected to F1]*/
         PORT_F_ID,PIN_F2_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_F_ID,PIN_F3_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_F_ID,PIN_F4_ID,PORT_PIN_IN,DIO_MODE,STD_HIGH,INTERNAL_PULL_UP,STD_LOW,STD_LOW,           /*[BUTTON Connected to F4]*/
         PORT_F_ID,PIN_F5_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_F_ID,PIN_F6_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
         PORT_F_ID,PIN_F7_ID,PORT_PIN_IN,DIO_MODE,STD_LOW,DISABLE_INTERNAL_RESISTOR,STD_HIGH,STD_HIGH,
        
};

  